apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-argocd-k8s-githubactions-kustomize-kyverno05
  namespace: davtrografanalokitempo
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno05
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-argocd-k8s-githubactions-kustomize-kyverno05
  template:
    metadata:
      labels:
        app: website-argocd-k8s-githubactions-kustomize-kyverno05
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: website-argocd-k8s-githubactions-kustomize-kyverno05-sa
      initContainers:
      - name: wait-for-db
        image: postgres:15
        command: 
        - sh
        - -c
        - |
          # Najpierw czekaj na serwer PostgreSQL
          until pg_isready -h postgres-service -p 5432; do
            echo "Waiting for PostgreSQL server...";
            sleep 2;
          done;
          
          # Potem czekaj aż baza davtro_db będzie dostępna
          until PGPASSWORD=password123 psql -h postgres-service -U davtro -d davtro_db -c "SELECT 1;" >/dev/null 2>&1; do
            echo "Waiting for database davtro_db to be ready...";
            sleep 2;
          done;
          
          echo "Database davtro_db is ready!"
        env:
        - name: PGPASSWORD
          value: "password123"
      containers:
      - name: website
        image: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno05:latest
        ports:
        - containerPort: 8090
        env:
        - name: PORT
          value: "8090"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "davtro"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "davtro_db"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
