apiVersion: v1
kind: ServiceAccount
metadata:
  name: website-argocd-k8s-githubactions-kustomize-kyverno05-sa
  namespace: davtrografanalokitempo
  labels:
    app: website-argocd-k8s-githubactions-kustomize-kyverno05
    version: v1
