apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: davtrografanalokitempo
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      log_level: info

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      max_block_duration: 5m
      trace_idle_period: 10s

    compactor:
      compaction:
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
