name: CI - build & update kustomize

on:
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "manifests/production/**"
  workflow_dispatch:

env:
  IMAGE_NAME: website-argocd-k8s-githubactions-kustomize-kyverno05
  KUSTOMIZE_PATH: manifests/production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Ensure static directory exists
        run: |
          mkdir -p static/css static/js
          if [ ! -f "static/css/style.css" ]; then
            echo "Creating default CSS..."
            echo "body { margin: 0; padding: 20px; font-family: sans-serif; }" > static/css/style.css
          fi
          if [ ! -f "static/js/app.js" ]; then
            echo "// Default app.js" > static/js/app.js
          fi

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Prepare Go modules
        run: |
          cd src
          go mod tidy
          go mod download

      - name: Build Go application
        run: |
          cd src
          go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update Kustomize image tag
        run: |
          cd ${{ env.KUSTOMIZE_PATH }}
          kustomize edit set image ${{ env.IMAGE_NAME }}=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.KUSTOMIZE_PATH }}/kustomization.yaml
          git diff --staged --quiet || git commit -m "ci: update image tag to ${{ github.sha }}"
          git push
